# Identificador único de tu proyecto en SonarCloud
sonar.projectKey=MarcoInfanteAgurto_AS241S5_AEJ_20-fe
sonar.organization=marcoinfanteagurto

# Nombre del proyecto mostrado en SonarCloud
sonar.projectName=AS241S5_AEJ_20-fe

# Rutas de código fuente y exclusiones
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,src/test.ts

# Codificación de archivos
sonar.sourceEncoding=UTF-8
